# Generated by Django 4.2.7 on 2025-12-12 18:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Battery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serial_number", models.CharField(max_length=100, unique=True)),
                ("battery_type", models.CharField(max_length=50)),
                ("capacity", models.FloatField(help_text="Battery capacity in mAh")),
                (
                    "voltage_nominal",
                    models.FloatField(help_text="Nominal voltage in volts"),
                ),
                (
                    "current_charge",
                    models.FloatField(
                        help_text="Current charge percentage (0-100%)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "current_voltage",
                    models.FloatField(help_text="Current voltage in volts"),
                ),
                (
                    "current_temperature",
                    models.FloatField(help_text="Temperature in Celsius"),
                ),
                (
                    "current_status",
                    models.CharField(
                        choices=[
                            ("CHARGING", "Charging"),
                            ("DISCHARGING", "Discharging"),
                            ("IDLE", "Idle"),
                            ("FAULT", "Fault"),
                        ],
                        default="IDLE",
                        max_length=20,
                    ),
                ),
                (
                    "health_percentage",
                    models.FloatField(
                        default=100,
                        help_text="Battery health percentage (0-100%)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "cycle_count",
                    models.IntegerField(default=0, help_text="Number of charge cycles"),
                ),
                (
                    "max_discharge_current",
                    models.FloatField(help_text="Max discharge current in Amps"),
                ),
                (
                    "max_charge_current",
                    models.FloatField(help_text="Max charge current in Amps"),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Battery",
                "verbose_name_plural": "Batteries",
                "ordering": ["-last_updated"],
            },
        ),
        migrations.CreateModel(
            name="BatteryDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_name", models.CharField(max_length=200)),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("MOBILE", "Mobile Phone"),
                            ("LAPTOP", "Laptop"),
                            ("DRONE", "Drone"),
                            ("VEHICLE", "Vehicle"),
                            ("INDUSTRIAL", "Industrial Equipment"),
                            ("OTHER", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("serial_number", models.CharField(max_length=100, unique=True)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_checked", models.DateTimeField(blank=True, null=True)),
                (
                    "batteries",
                    models.ManyToManyField(
                        related_name="devices", to="batteries.battery"
                    ),
                ),
            ],
            options={
                "verbose_name": "Battery Device",
                "verbose_name_plural": "Battery Devices",
                "ordering": ["device_name"],
            },
        ),
        migrations.CreateModel(
            name="BatteryAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("LOW_CHARGE", "Low Charge"),
                            ("OVERCHARGE", "Overcharge"),
                            ("OVER_TEMPERATURE", "Over Temperature"),
                            ("UNDER_VOLTAGE", "Under Voltage"),
                            ("OVER_CURRENT", "Over Current"),
                            ("HEALTH_DEGRADATION", "Health Degradation"),
                            ("FAULT", "Fault Detected"),
                            ("COMMUNICATION_ERROR", "Communication Error"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "alert_level",
                    models.CharField(
                        choices=[
                            ("INFO", "Information"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                            ("CRITICAL", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("is_resolved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "battery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="batteries.battery",
                    ),
                ),
            ],
            options={
                "verbose_name": "Battery Alert",
                "verbose_name_plural": "Battery Alerts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BatteryLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("charge_percentage", models.FloatField()),
                ("voltage", models.FloatField()),
                ("temperature", models.FloatField()),
                (
                    "current",
                    models.FloatField(
                        help_text="Positive for charging, negative for discharging"
                    ),
                ),
                ("status", models.CharField(max_length=20)),
                ("logged_at", models.DateTimeField(auto_now_add=True)),
                (
                    "battery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="batteries.battery",
                    ),
                ),
            ],
            options={
                "verbose_name": "Battery Log",
                "verbose_name_plural": "Battery Logs",
                "ordering": ["-logged_at"],
                "indexes": [
                    models.Index(
                        fields=["battery", "-logged_at"],
                        name="batteries_b_battery_84d161_idx",
                    )
                ],
            },
        ),
    ]
